export const orders = [
    {
        id: "1",
        company: "ABC Food",
        address: "460 Ang Mo Kio Avenue 10",
        name: "Alice",
        phoneNo: "62252617",
    },
    {
        id: "2",
        company: "North-East Catering",
        address: "Blk 678A Woodlands Ave 6 #01-15 S()",
        name: "Bob",
        phoneNo: "68939496",
    },
    {
        id: "3",
        company: "Elise Kitchen",
        address: "5028 Ang Mo Kio Industrial Park 2 01-185",
        name: "Charlie",
        phoneNo: "67522637",
    },
    {
        id: "4",
        company: "Saizeriya",
        address: "1033 Eunos Avenue 5A 01-19",
        name: "Desmond",
        phoneNo: "67522637",
    },
    {
        id: "5",
        company: "MacDonalds",
        address: "Signode 2 Joo Koon Circle",
        name: "Eric",
        phoneNo: "67522637",
    },
    {
        id: "6",
        company: "Shake Shack",
        address: "7 Keppel Road #02-18/20 Tanjong Pagar Complex",
        name: "Farhanah",
        phoneNo: "67522637",
    },
    {
        id: "7",
        company: "Yoshinoya",
        address: "BLK 1012 EUNOS AVENUE 6 01-11/15",
        name: "Gerald",
        phoneNo: "67522637",
    },
    {
        id: "8",
        company: "Swee Choon Dim Sum",
        address: "Blk 502, Jelapang Road, ,02-386",
        name: "Howard",
        phoneNo: "67522637",
    },
    {
        id: "9",
        company: "Lao Shu's Chwee Kueh",
        address: "8 Temasek Boulevard Suntec Tower Three",
        name: "Isacc",
        phoneNo: "67522637",
    },
]